# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/const.xdc

# Block Designs: bd/feedclock/feedclock.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==feedclock || ORIG_REF_NAME==feedclock} -quiet] -quiet

# IP: bd/feedclock/ip/feedclock_clk_wiz_0_0/feedclock_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==feedclock_clk_wiz_0_0 || ORIG_REF_NAME==feedclock_clk_wiz_0_0} -quiet] -quiet

# XDC: /home/eiffel/flattened_butterfly_NoC/flattened_butterfly_NoC.gen/sources_1/bd/feedclock/feedclock_ooc.xdc
