# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/eiffel/flattened_butterfly_NoC/flattened_butterfly_NoC.srcs/sources_1/bd/feedclock/ip/feedclock_clk_wiz_0_0/feedclock_clk_wiz_0_0.xci
# IP: The module: 'feedclock_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/eiffel/flattened_butterfly_NoC/flattened_butterfly_NoC.gen/sources_1/bd/feedclock/ip/feedclock_clk_wiz_0_0/feedclock_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'feedclock_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/eiffel/flattened_butterfly_NoC/flattened_butterfly_NoC.gen/sources_1/bd/feedclock/ip/feedclock_clk_wiz_0_0/feedclock_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'feedclock_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/eiffel/flattened_butterfly_NoC/flattened_butterfly_NoC.gen/sources_1/bd/feedclock/ip/feedclock_clk_wiz_0_0/feedclock_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'feedclock_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/eiffel/flattened_butterfly_NoC/flattened_butterfly_NoC.srcs/sources_1/bd/feedclock/ip/feedclock_clk_wiz_0_0/feedclock_clk_wiz_0_0.xci
# IP: The module: 'feedclock_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/eiffel/flattened_butterfly_NoC/flattened_butterfly_NoC.gen/sources_1/bd/feedclock/ip/feedclock_clk_wiz_0_0/feedclock_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'feedclock_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/eiffel/flattened_butterfly_NoC/flattened_butterfly_NoC.gen/sources_1/bd/feedclock/ip/feedclock_clk_wiz_0_0/feedclock_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'feedclock_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/eiffel/flattened_butterfly_NoC/flattened_butterfly_NoC.gen/sources_1/bd/feedclock/ip/feedclock_clk_wiz_0_0/feedclock_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'feedclock_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
